2021-09-02 04:27:42PM :: INFO :: Script started for today.
2021-09-02 04:27:42PM :: INFO :: Starting!!! Script For Automating ROLE is Starting For Today......
2021-09-02 04:27:42PM :: INFO :: Starting Session ......
2021-09-02 04:27:42PM :: ERROR :: Error : Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
 at automate_attendance
Stack (most recent call last):
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 2173, in <module>
    main()
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/anujs/PycharmProjects/Automate_ROLE/role/run.py", line 90, in <module>
    main()
  File "C:/Users/anujs/PycharmProjects/Automate_ROLE/role/run.py", line 59, in main
    automate_attendance(cwdir_name=cwd_name, username=user_name, password=user_pass)
  File "C:/Users/anujs/PycharmProjects/Automate_ROLE/role/run.py", line 40, in automate_attendance
    logging.error(f"Error : {error} at automate_attendance", stack_info=True)
2021-09-02 04:28:12PM :: INFO :: Starting Session ......
2021-09-02 04:28:12PM :: ERROR :: Error : Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
 at automate_attendance
Stack (most recent call last):
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 2173, in <module>
    main()
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/anujs/PycharmProjects/Automate_ROLE/role/run.py", line 90, in <module>
    main()
  File "C:/Users/anujs/PycharmProjects/Automate_ROLE/role/run.py", line 59, in main
    automate_attendance(cwdir_name=cwd_name, username=user_name, password=user_pass)
  File "C:/Users/anujs/PycharmProjects/Automate_ROLE/role/run.py", line 40, in automate_attendance
    logging.error(f"Error : {error} at automate_attendance", stack_info=True)
2021-09-02 04:28:25PM :: INFO :: Script started for today.
2021-09-02 04:28:25PM :: INFO :: Starting!!! Script For Automating ROLE is Starting For Today......
2021-09-02 04:28:25PM :: INFO :: Starting Session ......
2021-09-02 04:28:25PM :: ERROR :: Error : Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
 at automate_attendance
Stack (most recent call last):
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 2173, in <module>
    main()
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\anujs\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\212.4746.96\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/anujs/PycharmProjects/Automate_ROLE/role/run.py", line 90, in <module>
    main()
  File "C:/Users/anujs/PycharmProjects/Automate_ROLE/role/run.py", line 59, in main
    automate_attendance(cwdir_name=cwd_name, username=user_name, password=user_pass)
  File "C:/Users/anujs/PycharmProjects/Automate_ROLE/role/run.py", line 40, in automate_attendance
    logging.error(f"Error : {error} at automate_attendance", stack_info=True)
